=== sdrev/BBDD-PER5784-2223/Tema_2/Carlos Visdomine/PizzaSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="pizzas"/>
    <xs:element name="pizza">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="5"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
    <xs:attribute name="nombre" type="xs:string" use="required"/>
    <xs:attribute name="precio" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="vegan" type="xs:boolean" use="required"/>
  </xs:complexType>
</xs:element>
</xs:schema>

=== sdrev/BBDD-PER5784-2223/Tema_2/Carlos Visdomine/PizzaCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizzas
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="PizzaSchema.xsd">
<pizza nombre="carnivora" precio="25" vegan="false">
    <ingredientes>
        <nombre>peperoni</nombre>
    </ingredientes>
</pizza>
<pizza nombre="bbq" precio="18" vegan="false">
    <ingredientes>
        <nombre>beacon</nombre>
        <nombre>pollo</nombre>
    </ingredientes>
</pizza>
<pizza nombre="hawaiana" precio="12" vegan="false">
    <ingredientes>
        <nombre>pi√±a</nombre>
        <nombre>jamon york</nombre>
        <nombre>queso</nombre>
    </ingredientes>
</pizza>
<pizza nombre="especial" precio="30" vegan="false">
    <ingredientes>
        <nombre>aceituna</nombre>
        <nombre>beacon</nombre>
        <nombre>queso</nombre>
        <nombre>tomate</nombre>
        <nombre>salsa especial</nombre>
    </ingredientes>
</pizza>
</pizzas>
